config:
  cloudflare:apiToken:
    secure: AAABAJ3NqtNcnjdYwsl5CVpw1De6l4XKeGNDOLoFUAoX0Pu7ARMtHWEnbTLxHJBhNlpoEMcK0KSlmqCJh1v6lefFDHJG9W0mMPeUORtr5ymRlhLVxA==
  rshogi-csa-server-workers:accountId: d5d9818649d8722f73cd798c3b1ffb70
  rshogi-csa-server-workers:alertWebhookName: rshogi-staging-alerts
  rshogi-csa-server-workers:alertWebhookUrl:
    secure: AAABAJRIXz3HNNN7Ee63ZcCNZb3crM+TvlRigLWVyvhW6weOPtMI3g/w10UPi+t3X7d9t1yGj38QS5dkY5jyD+UFkV17QGK4FZXBrFVSbd/CDMSJJmUEWEAzpL66NgtGddcuqPRrKBMRB5DnokLySYc=
  rshogi-csa-server-workers:notificationsEnabled: "false"
